version: '3'

name: file-off
services:
  file-off-db:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  file-off-api:
    image: file-off-api
    build:
      context: api/
    ports:
      - 8080:8080
    environment:
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET:-123}
      - DB_URL=mongodb://mongoadmin:${MONGO_INITDB_ROOT_PASSWORD}@file-off-db:27017/file-off?authSource=admin
      - PORT=8080
    depends_on:
      - file-off-db

  file-off-client:
    image: todo-app-client
    build:
      context: client/
    depends_on:
      - file-off-api
