version: '3'

name: file-off
services:
  db:
    image: mongo:5.0.6
    restart: always
    ports:
      - 27017:27017

  api:
    build:
      context: api/
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET:-123}
      - DB_URL=mongodb://db:27017/file-off
      - PORT=8080

  client:
    build:
      context: client/
    depends_on:
      - api
