version: '3'

name: file-off-production
services:
  file-off-db:
    container_name: file-off-db

  file-off-api:
    container_name: file-off-api
    build:
      dockerfile: dockerfile.production
    environment:
      - NODE_ENV=production
      - CORS_ALLOW_ORIGINS=http://localhost:8081

  file-off-client:
    container_name: file-off-client
    build:
      dockerfile: dockerfile.production
      args:
        API_URL: http://localhost:8080/api
    ports:
      - 8081:80
    environment:
      - NODE_ENV=production
