version: '3'

name: file-off-development
services:
  file-off-db:
    container_name: file-off-db-dev

  file-off-api:
    container_name: file-off-api-dev
    image: file-off-api-dev
    build:
      dockerfile: dockerfile.development
    environment:
      - NODE_ENV=development
      - CORS_ALLOW_ORIGINS=http://localhost:8000
    volumes:
      - ./api:/app/
      - /app/node_modules

  file-off-client:
    container_name: file-off-client-dev
    image: file-off-client-dev
    build:
      dockerfile: dockerfile.development
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080/api
      - VITE_PORT=8000
    volumes:
      - ./client:/app/
      - /app/node_modules
