export interface Lang {
    LANG_RU: string;
    LANG_EN: string;

    LOGIN_PAGE_TITLE: string;
    LOGIN_PAGE_LOGIN_LABEL: string;
    LOGIN_PAGE_PASSWORD_LABEL: string;
    LOGIN_PAGE_REMEMBER_LABEL: string;
    LOGIN_PAGE_LOGIN_BUTTON: string;
    LOGIN_PAGE_ERROR_MESSAGE: string;
    LOGIN_PAGE_REGISTER_MESSAGE: string;
    LOGIN_PAGE_REGISTER_MESSAGE_LINK: string;

    REGISTER_PAGE_TITLE: string;
    REGISTER_PAGE_NAME_LABEL: string;
    REGISTER_PAGE_SURNAME_LABEL: string;
    REGISTER_PAGE_LOGIN_LABEL: string;
    REGISTER_PAGE_EMAIL_LABEL: string;
    REGISTER_PAGE_PASSWORD_LABEL: string;
    REGISTER_PAGE_CONFIRM_PASSWORD_LABEL: string;
    REGISTER_PAGE_REGISTER_BUTTON: string;
    REGISTER_PAGE_COMPLETE_MESSAGE: string;
    REGISTER_PAGE_COMPLETE_MESSAGE_DESCR: string;
    REGISTER_PAGE_PASSWORD_MATCH_ERROR: string;

    FILES_PAGE_TITLE: string;
    FILES_PAGE_FILE_ADD: string;
    FILES_PAGE_MODAL_ERROR_TITLE: string;
    FILES_PAGE_EMPTY: string;
    FILES_PAGE_DRAG_TITLE: string;
    FILES_PAGE_DRAG_ERROR_MANY_FILES: string;

    DOWNLOADS_PAGE_TITLE: string;

    FILE_CARD_DESCR_TITLE: string;
    FILE_CARD_DESCR_UPLOAD_DATE: string;
    FILE_CARD_DESCR_SENDER: string;
    FILE_CARD_DESCR_EXPIRE_DATE: string;
    FILE_CARD_DOWNLOAD_BUTTON: string;
    FILE_CARD_ACTIONS_TITLE: string;
    FILE_CARD_ACTIONS_DELETE: string;

    SIDEBAR_MENU_FILES_PAGE: string;
    SIDEBAR_MENU_DOWNLOADS_PAGE: string;

    PROFILE_MENU_EXIT: string;

    MODAL_UPLOAD_TITLE: string;
    MODAL_UPLOAD_FILE_LABEL: string;
    MODAL_UPLOAD_FILE_SELECTED_TITLE: string;
    MODAL_UPLOAD_FILE_SELECTED_NOT: string;
    MODAL_UPLOAD_FILE_CHANGE_BUTTON: string;
    MODAL_UPLOAD_RECIEVER_LABEL: string;
    MODAL_UPLOAD_EXPIRE_LABEL: string;
    MODAL_UPLOAD_EXPIRE_WEEK: string;
    MODAL_UPLOAD_EXPIRE_MONTH: string;
    MODAL_UPLOAD_EXPIRE_YEAR: string;
    MODAL_UPLOAD_FILE_UPLOAD_BUTTON: string;
    MODAL_UPLOAD_ERROR_TITLE: string;
    MODAL_UPLOAD_STATUS_LABEL: string;
    MODAL_UPLOAD_STATUS_LOADING: string;
    MODAL_UPLOAD_STATUS_DONE: string;

    API_ERROR_RECIEVER_404: string;
    API_ERROR_RECIEVER_EMPTY: string;

    API_ERROR_FILE_404: string;
    API_ERROR_FILES_404: string;
    API_ERROR_FILE_UPLOAD: string;

    API_ERROR_EMAIL_EXISTS: string;
    API_ERROR_EMAIL_EMPTY: string;
    API_ERROR_EMAIL_INVALID: string;

    API_ERROR_LOGIN_EXISTS: string;
    API_ERROR_LOGIN_EMPTY: string;

    API_ERROR_NAME_EMPTY: string;
    API_ERROR_SURNAME_EMPTY: string;
    API_ERROR_FILENAME_EMPTY: string;

    API_ERROR_PASSWORD_EMPTY: string;
    API_ERROR_PASSWORD_SHORT: string;

    API_ERROR_EXPIRE_EMPTY: string;
    API_ERROR_EXPIRE_INVALID: string;

    API_UPLOAD_FILE_ERROR: string;
    API_UPLOAD_FILE_ERROR_FILE_EXISTS: string;
    API_UPLOAD_FILE_ERROR_RECIEVER_EQUAL: string;

    API_DELETE_FILE_ERROR: string;
    API_DELETE_FILE_DONE: string;

    API_USER_CREATE_ERROR: string;
    API_USER_CREATE_DONE: string;

    API_AUTH_FAILED: string;
    API_AUTH_DONE: string;
}

export interface Langs {
    en: Lang;
    ru: Lang;
}
